package com.dota2.proto;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dota_modifiers.proto

public final class DotaModifiers {
  private DotaModifiers() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum DOTA_MODIFIER_ENTRY_TYPE
      implements com.google.protobuf.ProtocolMessageEnum {
    DOTA_MODIFIER_ENTRY_TYPE_ACTIVE(0, 1),
    DOTA_MODIFIER_ENTRY_TYPE_REMOVED(1, 2),
    ;
    
    public static final int DOTA_MODIFIER_ENTRY_TYPE_ACTIVE_VALUE = 1;
    public static final int DOTA_MODIFIER_ENTRY_TYPE_REMOVED_VALUE = 2;
    
    
    public final int getNumber() { return value; }
    
    public static DOTA_MODIFIER_ENTRY_TYPE valueOf(int value) {
      switch (value) {
        case 1: return DOTA_MODIFIER_ENTRY_TYPE_ACTIVE;
        case 2: return DOTA_MODIFIER_ENTRY_TYPE_REMOVED;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<DOTA_MODIFIER_ENTRY_TYPE>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<DOTA_MODIFIER_ENTRY_TYPE>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DOTA_MODIFIER_ENTRY_TYPE>() {
            public DOTA_MODIFIER_ENTRY_TYPE findValueByNumber(int number) {
              return DOTA_MODIFIER_ENTRY_TYPE.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return DotaModifiers.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final DOTA_MODIFIER_ENTRY_TYPE[] VALUES = {
      DOTA_MODIFIER_ENTRY_TYPE_ACTIVE, DOTA_MODIFIER_ENTRY_TYPE_REMOVED, 
    };
    
    public static DOTA_MODIFIER_ENTRY_TYPE valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private DOTA_MODIFIER_ENTRY_TYPE(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:DOTA_MODIFIER_ENTRY_TYPE)
  }
  
  public interface CDOTAModifierBuffTableEntryOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .DOTA_MODIFIER_ENTRY_TYPE entry_type = 1 [default = DOTA_MODIFIER_ENTRY_TYPE_ACTIVE];
    boolean hasEntryType();
    DotaModifiers.DOTA_MODIFIER_ENTRY_TYPE getEntryType();
    
    // required int32 parent = 2;
    boolean hasParent();
    int getParent();
    
    // required int32 index = 3;
    boolean hasIndex();
    int getIndex();
    
    // required int32 serial_num = 4;
    boolean hasSerialNum();
    int getSerialNum();
    
    // optional int32 modifier_class = 5;
    boolean hasModifierClass();
    int getModifierClass();
    
    // optional int32 ability_level = 6;
    boolean hasAbilityLevel();
    int getAbilityLevel();
    
    // optional int32 stack_count = 7;
    boolean hasStackCount();
    int getStackCount();
    
    // optional float creation_time = 8;
    boolean hasCreationTime();
    float getCreationTime();
    
    // optional float duration = 9 [default = -1];
    boolean hasDuration();
    float getDuration();
    
    // optional int32 caster = 10;
    boolean hasCaster();
    int getCaster();
    
    // optional int32 ability = 11;
    boolean hasAbility();
    int getAbility();
    
    // optional int32 armor = 12;
    boolean hasArmor();
    int getArmor();
    
    // optional float fade_time = 13;
    boolean hasFadeTime();
    float getFadeTime();
    
    // optional bool subtle = 14;
    boolean hasSubtle();
    boolean getSubtle();
    
    // optional float channel_time = 15;
    boolean hasChannelTime();
    float getChannelTime();
    
    // optional .CMsgVector v_start = 16;
    boolean hasVStart();
    Networkbasetypes.CMsgVector getVStart();
    Networkbasetypes.CMsgVectorOrBuilder getVStartOrBuilder();
    
    // optional .CMsgVector v_end = 17;
    boolean hasVEnd();
    Networkbasetypes.CMsgVector getVEnd();
    Networkbasetypes.CMsgVectorOrBuilder getVEndOrBuilder();
    
    // optional string portal_loop_appear = 18;
    boolean hasPortalLoopAppear();
    String getPortalLoopAppear();
    
    // optional string portal_loop_disappear = 19;
    boolean hasPortalLoopDisappear();
    String getPortalLoopDisappear();
    
    // optional string hero_loop_appear = 20;
    boolean hasHeroLoopAppear();
    String getHeroLoopAppear();
    
    // optional string hero_loop_disappear = 21;
    boolean hasHeroLoopDisappear();
    String getHeroLoopDisappear();
    
    // optional int32 movement_speed = 22;
    boolean hasMovementSpeed();
    int getMovementSpeed();
    
    // optional bool aura = 23;
    boolean hasAura();
    boolean getAura();
    
    // optional int32 activity = 24;
    boolean hasActivity();
    int getActivity();
    
    // optional int32 damage = 25;
    boolean hasDamage();
    int getDamage();
    
    // optional int32 range = 26;
    boolean hasRange();
    int getRange();
    
    // optional int32 dd_modifier_index = 27;
    boolean hasDdModifierIndex();
    int getDdModifierIndex();
    
    // optional int32 dd_ability_index = 28;
    boolean hasDdAbilityIndex();
    int getDdAbilityIndex();
  }
  public static final class CDOTAModifierBuffTableEntry extends
      com.google.protobuf.GeneratedMessage
      implements CDOTAModifierBuffTableEntryOrBuilder {
    // Use CDOTAModifierBuffTableEntry.newBuilder() to construct.
    private CDOTAModifierBuffTableEntry(Builder builder) {
      super(builder);
    }
    private CDOTAModifierBuffTableEntry(boolean noInit) {}
    
    private static final CDOTAModifierBuffTableEntry defaultInstance;
    public static CDOTAModifierBuffTableEntry getDefaultInstance() {
      return defaultInstance;
    }
    
    public CDOTAModifierBuffTableEntry getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DotaModifiers.internal_static_CDOTAModifierBuffTableEntry_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DotaModifiers.internal_static_CDOTAModifierBuffTableEntry_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required .DOTA_MODIFIER_ENTRY_TYPE entry_type = 1 [default = DOTA_MODIFIER_ENTRY_TYPE_ACTIVE];
    public static final int ENTRY_TYPE_FIELD_NUMBER = 1;
    private DotaModifiers.DOTA_MODIFIER_ENTRY_TYPE entryType_;
    public boolean hasEntryType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public DotaModifiers.DOTA_MODIFIER_ENTRY_TYPE getEntryType() {
      return entryType_;
    }
    
    // required int32 parent = 2;
    public static final int PARENT_FIELD_NUMBER = 2;
    private int parent_;
    public boolean hasParent() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getParent() {
      return parent_;
    }
    
    // required int32 index = 3;
    public static final int INDEX_FIELD_NUMBER = 3;
    private int index_;
    public boolean hasIndex() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getIndex() {
      return index_;
    }
    
    // required int32 serial_num = 4;
    public static final int SERIAL_NUM_FIELD_NUMBER = 4;
    private int serialNum_;
    public boolean hasSerialNum() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getSerialNum() {
      return serialNum_;
    }
    
    // optional int32 modifier_class = 5;
    public static final int MODIFIER_CLASS_FIELD_NUMBER = 5;
    private int modifierClass_;
    public boolean hasModifierClass() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getModifierClass() {
      return modifierClass_;
    }
    
    // optional int32 ability_level = 6;
    public static final int ABILITY_LEVEL_FIELD_NUMBER = 6;
    private int abilityLevel_;
    public boolean hasAbilityLevel() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public int getAbilityLevel() {
      return abilityLevel_;
    }
    
    // optional int32 stack_count = 7;
    public static final int STACK_COUNT_FIELD_NUMBER = 7;
    private int stackCount_;
    public boolean hasStackCount() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public int getStackCount() {
      return stackCount_;
    }
    
    // optional float creation_time = 8;
    public static final int CREATION_TIME_FIELD_NUMBER = 8;
    private float creationTime_;
    public boolean hasCreationTime() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public float getCreationTime() {
      return creationTime_;
    }
    
    // optional float duration = 9 [default = -1];
    public static final int DURATION_FIELD_NUMBER = 9;
    private float duration_;
    public boolean hasDuration() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public float getDuration() {
      return duration_;
    }
    
    // optional int32 caster = 10;
    public static final int CASTER_FIELD_NUMBER = 10;
    private int caster_;
    public boolean hasCaster() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    public int getCaster() {
      return caster_;
    }
    
    // optional int32 ability = 11;
    public static final int ABILITY_FIELD_NUMBER = 11;
    private int ability_;
    public boolean hasAbility() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    public int getAbility() {
      return ability_;
    }
    
    // optional int32 armor = 12;
    public static final int ARMOR_FIELD_NUMBER = 12;
    private int armor_;
    public boolean hasArmor() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    public int getArmor() {
      return armor_;
    }
    
    // optional float fade_time = 13;
    public static final int FADE_TIME_FIELD_NUMBER = 13;
    private float fadeTime_;
    public boolean hasFadeTime() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    public float getFadeTime() {
      return fadeTime_;
    }
    
    // optional bool subtle = 14;
    public static final int SUBTLE_FIELD_NUMBER = 14;
    private boolean subtle_;
    public boolean hasSubtle() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    public boolean getSubtle() {
      return subtle_;
    }
    
    // optional float channel_time = 15;
    public static final int CHANNEL_TIME_FIELD_NUMBER = 15;
    private float channelTime_;
    public boolean hasChannelTime() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    public float getChannelTime() {
      return channelTime_;
    }
    
    // optional .CMsgVector v_start = 16;
    public static final int V_START_FIELD_NUMBER = 16;
    private Networkbasetypes.CMsgVector vStart_;
    public boolean hasVStart() {
      return ((bitField0_ & 0x00008000) == 0x00008000);
    }
    public Networkbasetypes.CMsgVector getVStart() {
      return vStart_;
    }
    public Networkbasetypes.CMsgVectorOrBuilder getVStartOrBuilder() {
      return vStart_;
    }
    
    // optional .CMsgVector v_end = 17;
    public static final int V_END_FIELD_NUMBER = 17;
    private Networkbasetypes.CMsgVector vEnd_;
    public boolean hasVEnd() {
      return ((bitField0_ & 0x00010000) == 0x00010000);
    }
    public Networkbasetypes.CMsgVector getVEnd() {
      return vEnd_;
    }
    public Networkbasetypes.CMsgVectorOrBuilder getVEndOrBuilder() {
      return vEnd_;
    }
    
    // optional string portal_loop_appear = 18;
    public static final int PORTAL_LOOP_APPEAR_FIELD_NUMBER = 18;
    private java.lang.Object portalLoopAppear_;
    public boolean hasPortalLoopAppear() {
      return ((bitField0_ & 0x00020000) == 0x00020000);
    }
    public String getPortalLoopAppear() {
      java.lang.Object ref = portalLoopAppear_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          portalLoopAppear_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPortalLoopAppearBytes() {
      java.lang.Object ref = portalLoopAppear_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        portalLoopAppear_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string portal_loop_disappear = 19;
    public static final int PORTAL_LOOP_DISAPPEAR_FIELD_NUMBER = 19;
    private java.lang.Object portalLoopDisappear_;
    public boolean hasPortalLoopDisappear() {
      return ((bitField0_ & 0x00040000) == 0x00040000);
    }
    public String getPortalLoopDisappear() {
      java.lang.Object ref = portalLoopDisappear_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          portalLoopDisappear_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPortalLoopDisappearBytes() {
      java.lang.Object ref = portalLoopDisappear_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        portalLoopDisappear_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string hero_loop_appear = 20;
    public static final int HERO_LOOP_APPEAR_FIELD_NUMBER = 20;
    private java.lang.Object heroLoopAppear_;
    public boolean hasHeroLoopAppear() {
      return ((bitField0_ & 0x00080000) == 0x00080000);
    }
    public String getHeroLoopAppear() {
      java.lang.Object ref = heroLoopAppear_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          heroLoopAppear_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getHeroLoopAppearBytes() {
      java.lang.Object ref = heroLoopAppear_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        heroLoopAppear_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string hero_loop_disappear = 21;
    public static final int HERO_LOOP_DISAPPEAR_FIELD_NUMBER = 21;
    private java.lang.Object heroLoopDisappear_;
    public boolean hasHeroLoopDisappear() {
      return ((bitField0_ & 0x00100000) == 0x00100000);
    }
    public String getHeroLoopDisappear() {
      java.lang.Object ref = heroLoopDisappear_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          heroLoopDisappear_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getHeroLoopDisappearBytes() {
      java.lang.Object ref = heroLoopDisappear_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        heroLoopDisappear_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 movement_speed = 22;
    public static final int MOVEMENT_SPEED_FIELD_NUMBER = 22;
    private int movementSpeed_;
    public boolean hasMovementSpeed() {
      return ((bitField0_ & 0x00200000) == 0x00200000);
    }
    public int getMovementSpeed() {
      return movementSpeed_;
    }
    
    // optional bool aura = 23;
    public static final int AURA_FIELD_NUMBER = 23;
    private boolean aura_;
    public boolean hasAura() {
      return ((bitField0_ & 0x00400000) == 0x00400000);
    }
    public boolean getAura() {
      return aura_;
    }
    
    // optional int32 activity = 24;
    public static final int ACTIVITY_FIELD_NUMBER = 24;
    private int activity_;
    public boolean hasActivity() {
      return ((bitField0_ & 0x00800000) == 0x00800000);
    }
    public int getActivity() {
      return activity_;
    }
    
    // optional int32 damage = 25;
    public static final int DAMAGE_FIELD_NUMBER = 25;
    private int damage_;
    public boolean hasDamage() {
      return ((bitField0_ & 0x01000000) == 0x01000000);
    }
    public int getDamage() {
      return damage_;
    }
    
    // optional int32 range = 26;
    public static final int RANGE_FIELD_NUMBER = 26;
    private int range_;
    public boolean hasRange() {
      return ((bitField0_ & 0x02000000) == 0x02000000);
    }
    public int getRange() {
      return range_;
    }
    
    // optional int32 dd_modifier_index = 27;
    public static final int DD_MODIFIER_INDEX_FIELD_NUMBER = 27;
    private int ddModifierIndex_;
    public boolean hasDdModifierIndex() {
      return ((bitField0_ & 0x04000000) == 0x04000000);
    }
    public int getDdModifierIndex() {
      return ddModifierIndex_;
    }
    
    // optional int32 dd_ability_index = 28;
    public static final int DD_ABILITY_INDEX_FIELD_NUMBER = 28;
    private int ddAbilityIndex_;
    public boolean hasDdAbilityIndex() {
      return ((bitField0_ & 0x08000000) == 0x08000000);
    }
    public int getDdAbilityIndex() {
      return ddAbilityIndex_;
    }
    
    private void initFields() {
      entryType_ = DotaModifiers.DOTA_MODIFIER_ENTRY_TYPE.DOTA_MODIFIER_ENTRY_TYPE_ACTIVE;
      parent_ = 0;
      index_ = 0;
      serialNum_ = 0;
      modifierClass_ = 0;
      abilityLevel_ = 0;
      stackCount_ = 0;
      creationTime_ = 0F;
      duration_ = -1F;
      caster_ = 0;
      ability_ = 0;
      armor_ = 0;
      fadeTime_ = 0F;
      subtle_ = false;
      channelTime_ = 0F;
      vStart_ = Networkbasetypes.CMsgVector.getDefaultInstance();
      vEnd_ = Networkbasetypes.CMsgVector.getDefaultInstance();
      portalLoopAppear_ = "";
      portalLoopDisappear_ = "";
      heroLoopAppear_ = "";
      heroLoopDisappear_ = "";
      movementSpeed_ = 0;
      aura_ = false;
      activity_ = 0;
      damage_ = 0;
      range_ = 0;
      ddModifierIndex_ = 0;
      ddAbilityIndex_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasEntryType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasParent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIndex()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSerialNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, entryType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, parent_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, index_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, serialNum_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, modifierClass_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, abilityLevel_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, stackCount_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeFloat(8, creationTime_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeFloat(9, duration_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt32(10, caster_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeInt32(11, ability_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeInt32(12, armor_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeFloat(13, fadeTime_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeBool(14, subtle_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        output.writeFloat(15, channelTime_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        output.writeMessage(16, vStart_);
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        output.writeMessage(17, vEnd_);
      }
      if (((bitField0_ & 0x00020000) == 0x00020000)) {
        output.writeBytes(18, getPortalLoopAppearBytes());
      }
      if (((bitField0_ & 0x00040000) == 0x00040000)) {
        output.writeBytes(19, getPortalLoopDisappearBytes());
      }
      if (((bitField0_ & 0x00080000) == 0x00080000)) {
        output.writeBytes(20, getHeroLoopAppearBytes());
      }
      if (((bitField0_ & 0x00100000) == 0x00100000)) {
        output.writeBytes(21, getHeroLoopDisappearBytes());
      }
      if (((bitField0_ & 0x00200000) == 0x00200000)) {
        output.writeInt32(22, movementSpeed_);
      }
      if (((bitField0_ & 0x00400000) == 0x00400000)) {
        output.writeBool(23, aura_);
      }
      if (((bitField0_ & 0x00800000) == 0x00800000)) {
        output.writeInt32(24, activity_);
      }
      if (((bitField0_ & 0x01000000) == 0x01000000)) {
        output.writeInt32(25, damage_);
      }
      if (((bitField0_ & 0x02000000) == 0x02000000)) {
        output.writeInt32(26, range_);
      }
      if (((bitField0_ & 0x04000000) == 0x04000000)) {
        output.writeInt32(27, ddModifierIndex_);
      }
      if (((bitField0_ & 0x08000000) == 0x08000000)) {
        output.writeInt32(28, ddAbilityIndex_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, entryType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, parent_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, index_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, serialNum_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, modifierClass_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, abilityLevel_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, stackCount_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(8, creationTime_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(9, duration_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, caster_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, ability_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(12, armor_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(13, fadeTime_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(14, subtle_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(15, channelTime_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(16, vStart_);
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(17, vEnd_);
      }
      if (((bitField0_ & 0x00020000) == 0x00020000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(18, getPortalLoopAppearBytes());
      }
      if (((bitField0_ & 0x00040000) == 0x00040000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(19, getPortalLoopDisappearBytes());
      }
      if (((bitField0_ & 0x00080000) == 0x00080000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(20, getHeroLoopAppearBytes());
      }
      if (((bitField0_ & 0x00100000) == 0x00100000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(21, getHeroLoopDisappearBytes());
      }
      if (((bitField0_ & 0x00200000) == 0x00200000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(22, movementSpeed_);
      }
      if (((bitField0_ & 0x00400000) == 0x00400000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(23, aura_);
      }
      if (((bitField0_ & 0x00800000) == 0x00800000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(24, activity_);
      }
      if (((bitField0_ & 0x01000000) == 0x01000000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(25, damage_);
      }
      if (((bitField0_ & 0x02000000) == 0x02000000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(26, range_);
      }
      if (((bitField0_ & 0x04000000) == 0x04000000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(27, ddModifierIndex_);
      }
      if (((bitField0_ & 0x08000000) == 0x08000000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(28, ddAbilityIndex_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static DotaModifiers.CDOTAModifierBuffTableEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static DotaModifiers.CDOTAModifierBuffTableEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static DotaModifiers.CDOTAModifierBuffTableEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static DotaModifiers.CDOTAModifierBuffTableEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static DotaModifiers.CDOTAModifierBuffTableEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static DotaModifiers.CDOTAModifierBuffTableEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static DotaModifiers.CDOTAModifierBuffTableEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static DotaModifiers.CDOTAModifierBuffTableEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static DotaModifiers.CDOTAModifierBuffTableEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static DotaModifiers.CDOTAModifierBuffTableEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(DotaModifiers.CDOTAModifierBuffTableEntry prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements DotaModifiers.CDOTAModifierBuffTableEntryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DotaModifiers.internal_static_CDOTAModifierBuffTableEntry_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DotaModifiers.internal_static_CDOTAModifierBuffTableEntry_fieldAccessorTable;
      }
      
      // Construct using DotaModifiers.CDOTAModifierBuffTableEntry.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getVStartFieldBuilder();
          getVEndFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        entryType_ = DotaModifiers.DOTA_MODIFIER_ENTRY_TYPE.DOTA_MODIFIER_ENTRY_TYPE_ACTIVE;
        bitField0_ = (bitField0_ & ~0x00000001);
        parent_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        index_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        serialNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        modifierClass_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        abilityLevel_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        stackCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        creationTime_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000080);
        duration_ = -1F;
        bitField0_ = (bitField0_ & ~0x00000100);
        caster_ = 0;
        bitField0_ = (bitField0_ & ~0x00000200);
        ability_ = 0;
        bitField0_ = (bitField0_ & ~0x00000400);
        armor_ = 0;
        bitField0_ = (bitField0_ & ~0x00000800);
        fadeTime_ = 0F;
        bitField0_ = (bitField0_ & ~0x00001000);
        subtle_ = false;
        bitField0_ = (bitField0_ & ~0x00002000);
        channelTime_ = 0F;
        bitField0_ = (bitField0_ & ~0x00004000);
        if (vStartBuilder_ == null) {
          vStart_ = Networkbasetypes.CMsgVector.getDefaultInstance();
        } else {
          vStartBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00008000);
        if (vEndBuilder_ == null) {
          vEnd_ = Networkbasetypes.CMsgVector.getDefaultInstance();
        } else {
          vEndBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00010000);
        portalLoopAppear_ = "";
        bitField0_ = (bitField0_ & ~0x00020000);
        portalLoopDisappear_ = "";
        bitField0_ = (bitField0_ & ~0x00040000);
        heroLoopAppear_ = "";
        bitField0_ = (bitField0_ & ~0x00080000);
        heroLoopDisappear_ = "";
        bitField0_ = (bitField0_ & ~0x00100000);
        movementSpeed_ = 0;
        bitField0_ = (bitField0_ & ~0x00200000);
        aura_ = false;
        bitField0_ = (bitField0_ & ~0x00400000);
        activity_ = 0;
        bitField0_ = (bitField0_ & ~0x00800000);
        damage_ = 0;
        bitField0_ = (bitField0_ & ~0x01000000);
        range_ = 0;
        bitField0_ = (bitField0_ & ~0x02000000);
        ddModifierIndex_ = 0;
        bitField0_ = (bitField0_ & ~0x04000000);
        ddAbilityIndex_ = 0;
        bitField0_ = (bitField0_ & ~0x08000000);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DotaModifiers.CDOTAModifierBuffTableEntry.getDescriptor();
      }
      
      public DotaModifiers.CDOTAModifierBuffTableEntry getDefaultInstanceForType() {
        return DotaModifiers.CDOTAModifierBuffTableEntry.getDefaultInstance();
      }
      
      public DotaModifiers.CDOTAModifierBuffTableEntry build() {
        DotaModifiers.CDOTAModifierBuffTableEntry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private DotaModifiers.CDOTAModifierBuffTableEntry buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        DotaModifiers.CDOTAModifierBuffTableEntry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public DotaModifiers.CDOTAModifierBuffTableEntry buildPartial() {
        DotaModifiers.CDOTAModifierBuffTableEntry result = new DotaModifiers.CDOTAModifierBuffTableEntry(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.entryType_ = entryType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.parent_ = parent_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.index_ = index_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.serialNum_ = serialNum_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.modifierClass_ = modifierClass_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.abilityLevel_ = abilityLevel_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.stackCount_ = stackCount_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.creationTime_ = creationTime_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.duration_ = duration_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.caster_ = caster_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.ability_ = ability_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.armor_ = armor_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.fadeTime_ = fadeTime_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.subtle_ = subtle_;
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00004000;
        }
        result.channelTime_ = channelTime_;
        if (((from_bitField0_ & 0x00008000) == 0x00008000)) {
          to_bitField0_ |= 0x00008000;
        }
        if (vStartBuilder_ == null) {
          result.vStart_ = vStart_;
        } else {
          result.vStart_ = vStartBuilder_.build();
        }
        if (((from_bitField0_ & 0x00010000) == 0x00010000)) {
          to_bitField0_ |= 0x00010000;
        }
        if (vEndBuilder_ == null) {
          result.vEnd_ = vEnd_;
        } else {
          result.vEnd_ = vEndBuilder_.build();
        }
        if (((from_bitField0_ & 0x00020000) == 0x00020000)) {
          to_bitField0_ |= 0x00020000;
        }
        result.portalLoopAppear_ = portalLoopAppear_;
        if (((from_bitField0_ & 0x00040000) == 0x00040000)) {
          to_bitField0_ |= 0x00040000;
        }
        result.portalLoopDisappear_ = portalLoopDisappear_;
        if (((from_bitField0_ & 0x00080000) == 0x00080000)) {
          to_bitField0_ |= 0x00080000;
        }
        result.heroLoopAppear_ = heroLoopAppear_;
        if (((from_bitField0_ & 0x00100000) == 0x00100000)) {
          to_bitField0_ |= 0x00100000;
        }
        result.heroLoopDisappear_ = heroLoopDisappear_;
        if (((from_bitField0_ & 0x00200000) == 0x00200000)) {
          to_bitField0_ |= 0x00200000;
        }
        result.movementSpeed_ = movementSpeed_;
        if (((from_bitField0_ & 0x00400000) == 0x00400000)) {
          to_bitField0_ |= 0x00400000;
        }
        result.aura_ = aura_;
        if (((from_bitField0_ & 0x00800000) == 0x00800000)) {
          to_bitField0_ |= 0x00800000;
        }
        result.activity_ = activity_;
        if (((from_bitField0_ & 0x01000000) == 0x01000000)) {
          to_bitField0_ |= 0x01000000;
        }
        result.damage_ = damage_;
        if (((from_bitField0_ & 0x02000000) == 0x02000000)) {
          to_bitField0_ |= 0x02000000;
        }
        result.range_ = range_;
        if (((from_bitField0_ & 0x04000000) == 0x04000000)) {
          to_bitField0_ |= 0x04000000;
        }
        result.ddModifierIndex_ = ddModifierIndex_;
        if (((from_bitField0_ & 0x08000000) == 0x08000000)) {
          to_bitField0_ |= 0x08000000;
        }
        result.ddAbilityIndex_ = ddAbilityIndex_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DotaModifiers.CDOTAModifierBuffTableEntry) {
          return mergeFrom((DotaModifiers.CDOTAModifierBuffTableEntry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(DotaModifiers.CDOTAModifierBuffTableEntry other) {
        if (other == DotaModifiers.CDOTAModifierBuffTableEntry.getDefaultInstance()) return this;
        if (other.hasEntryType()) {
          setEntryType(other.getEntryType());
        }
        if (other.hasParent()) {
          setParent(other.getParent());
        }
        if (other.hasIndex()) {
          setIndex(other.getIndex());
        }
        if (other.hasSerialNum()) {
          setSerialNum(other.getSerialNum());
        }
        if (other.hasModifierClass()) {
          setModifierClass(other.getModifierClass());
        }
        if (other.hasAbilityLevel()) {
          setAbilityLevel(other.getAbilityLevel());
        }
        if (other.hasStackCount()) {
          setStackCount(other.getStackCount());
        }
        if (other.hasCreationTime()) {
          setCreationTime(other.getCreationTime());
        }
        if (other.hasDuration()) {
          setDuration(other.getDuration());
        }
        if (other.hasCaster()) {
          setCaster(other.getCaster());
        }
        if (other.hasAbility()) {
          setAbility(other.getAbility());
        }
        if (other.hasArmor()) {
          setArmor(other.getArmor());
        }
        if (other.hasFadeTime()) {
          setFadeTime(other.getFadeTime());
        }
        if (other.hasSubtle()) {
          setSubtle(other.getSubtle());
        }
        if (other.hasChannelTime()) {
          setChannelTime(other.getChannelTime());
        }
        if (other.hasVStart()) {
          mergeVStart(other.getVStart());
        }
        if (other.hasVEnd()) {
          mergeVEnd(other.getVEnd());
        }
        if (other.hasPortalLoopAppear()) {
          setPortalLoopAppear(other.getPortalLoopAppear());
        }
        if (other.hasPortalLoopDisappear()) {
          setPortalLoopDisappear(other.getPortalLoopDisappear());
        }
        if (other.hasHeroLoopAppear()) {
          setHeroLoopAppear(other.getHeroLoopAppear());
        }
        if (other.hasHeroLoopDisappear()) {
          setHeroLoopDisappear(other.getHeroLoopDisappear());
        }
        if (other.hasMovementSpeed()) {
          setMovementSpeed(other.getMovementSpeed());
        }
        if (other.hasAura()) {
          setAura(other.getAura());
        }
        if (other.hasActivity()) {
          setActivity(other.getActivity());
        }
        if (other.hasDamage()) {
          setDamage(other.getDamage());
        }
        if (other.hasRange()) {
          setRange(other.getRange());
        }
        if (other.hasDdModifierIndex()) {
          setDdModifierIndex(other.getDdModifierIndex());
        }
        if (other.hasDdAbilityIndex()) {
          setDdAbilityIndex(other.getDdAbilityIndex());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasEntryType()) {
          
          return false;
        }
        if (!hasParent()) {
          
          return false;
        }
        if (!hasIndex()) {
          
          return false;
        }
        if (!hasSerialNum()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              DotaModifiers.DOTA_MODIFIER_ENTRY_TYPE value = DotaModifiers.DOTA_MODIFIER_ENTRY_TYPE.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                entryType_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              parent_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              index_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              serialNum_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              modifierClass_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              abilityLevel_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              stackCount_ = input.readInt32();
              break;
            }
            case 69: {
              bitField0_ |= 0x00000080;
              creationTime_ = input.readFloat();
              break;
            }
            case 77: {
              bitField0_ |= 0x00000100;
              duration_ = input.readFloat();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              caster_ = input.readInt32();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              ability_ = input.readInt32();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              armor_ = input.readInt32();
              break;
            }
            case 109: {
              bitField0_ |= 0x00001000;
              fadeTime_ = input.readFloat();
              break;
            }
            case 112: {
              bitField0_ |= 0x00002000;
              subtle_ = input.readBool();
              break;
            }
            case 125: {
              bitField0_ |= 0x00004000;
              channelTime_ = input.readFloat();
              break;
            }
            case 130: {
              Networkbasetypes.CMsgVector.Builder subBuilder = Networkbasetypes.CMsgVector.newBuilder();
              if (hasVStart()) {
                subBuilder.mergeFrom(getVStart());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setVStart(subBuilder.buildPartial());
              break;
            }
            case 138: {
              Networkbasetypes.CMsgVector.Builder subBuilder = Networkbasetypes.CMsgVector.newBuilder();
              if (hasVEnd()) {
                subBuilder.mergeFrom(getVEnd());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setVEnd(subBuilder.buildPartial());
              break;
            }
            case 146: {
              bitField0_ |= 0x00020000;
              portalLoopAppear_ = input.readBytes();
              break;
            }
            case 154: {
              bitField0_ |= 0x00040000;
              portalLoopDisappear_ = input.readBytes();
              break;
            }
            case 162: {
              bitField0_ |= 0x00080000;
              heroLoopAppear_ = input.readBytes();
              break;
            }
            case 170: {
              bitField0_ |= 0x00100000;
              heroLoopDisappear_ = input.readBytes();
              break;
            }
            case 176: {
              bitField0_ |= 0x00200000;
              movementSpeed_ = input.readInt32();
              break;
            }
            case 184: {
              bitField0_ |= 0x00400000;
              aura_ = input.readBool();
              break;
            }
            case 192: {
              bitField0_ |= 0x00800000;
              activity_ = input.readInt32();
              break;
            }
            case 200: {
              bitField0_ |= 0x01000000;
              damage_ = input.readInt32();
              break;
            }
            case 208: {
              bitField0_ |= 0x02000000;
              range_ = input.readInt32();
              break;
            }
            case 216: {
              bitField0_ |= 0x04000000;
              ddModifierIndex_ = input.readInt32();
              break;
            }
            case 224: {
              bitField0_ |= 0x08000000;
              ddAbilityIndex_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .DOTA_MODIFIER_ENTRY_TYPE entry_type = 1 [default = DOTA_MODIFIER_ENTRY_TYPE_ACTIVE];
      private DotaModifiers.DOTA_MODIFIER_ENTRY_TYPE entryType_ = DotaModifiers.DOTA_MODIFIER_ENTRY_TYPE.DOTA_MODIFIER_ENTRY_TYPE_ACTIVE;
      public boolean hasEntryType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public DotaModifiers.DOTA_MODIFIER_ENTRY_TYPE getEntryType() {
        return entryType_;
      }
      public Builder setEntryType(DotaModifiers.DOTA_MODIFIER_ENTRY_TYPE value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        entryType_ = value;
        onChanged();
        return this;
      }
      public Builder clearEntryType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        entryType_ = DotaModifiers.DOTA_MODIFIER_ENTRY_TYPE.DOTA_MODIFIER_ENTRY_TYPE_ACTIVE;
        onChanged();
        return this;
      }
      
      // required int32 parent = 2;
      private int parent_ ;
      public boolean hasParent() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getParent() {
        return parent_;
      }
      public Builder setParent(int value) {
        bitField0_ |= 0x00000002;
        parent_ = value;
        onChanged();
        return this;
      }
      public Builder clearParent() {
        bitField0_ = (bitField0_ & ~0x00000002);
        parent_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 index = 3;
      private int index_ ;
      public boolean hasIndex() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getIndex() {
        return index_;
      }
      public Builder setIndex(int value) {
        bitField0_ |= 0x00000004;
        index_ = value;
        onChanged();
        return this;
      }
      public Builder clearIndex() {
        bitField0_ = (bitField0_ & ~0x00000004);
        index_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 serial_num = 4;
      private int serialNum_ ;
      public boolean hasSerialNum() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getSerialNum() {
        return serialNum_;
      }
      public Builder setSerialNum(int value) {
        bitField0_ |= 0x00000008;
        serialNum_ = value;
        onChanged();
        return this;
      }
      public Builder clearSerialNum() {
        bitField0_ = (bitField0_ & ~0x00000008);
        serialNum_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 modifier_class = 5;
      private int modifierClass_ ;
      public boolean hasModifierClass() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getModifierClass() {
        return modifierClass_;
      }
      public Builder setModifierClass(int value) {
        bitField0_ |= 0x00000010;
        modifierClass_ = value;
        onChanged();
        return this;
      }
      public Builder clearModifierClass() {
        bitField0_ = (bitField0_ & ~0x00000010);
        modifierClass_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 ability_level = 6;
      private int abilityLevel_ ;
      public boolean hasAbilityLevel() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public int getAbilityLevel() {
        return abilityLevel_;
      }
      public Builder setAbilityLevel(int value) {
        bitField0_ |= 0x00000020;
        abilityLevel_ = value;
        onChanged();
        return this;
      }
      public Builder clearAbilityLevel() {
        bitField0_ = (bitField0_ & ~0x00000020);
        abilityLevel_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 stack_count = 7;
      private int stackCount_ ;
      public boolean hasStackCount() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public int getStackCount() {
        return stackCount_;
      }
      public Builder setStackCount(int value) {
        bitField0_ |= 0x00000040;
        stackCount_ = value;
        onChanged();
        return this;
      }
      public Builder clearStackCount() {
        bitField0_ = (bitField0_ & ~0x00000040);
        stackCount_ = 0;
        onChanged();
        return this;
      }
      
      // optional float creation_time = 8;
      private float creationTime_ ;
      public boolean hasCreationTime() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public float getCreationTime() {
        return creationTime_;
      }
      public Builder setCreationTime(float value) {
        bitField0_ |= 0x00000080;
        creationTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearCreationTime() {
        bitField0_ = (bitField0_ & ~0x00000080);
        creationTime_ = 0F;
        onChanged();
        return this;
      }
      
      // optional float duration = 9 [default = -1];
      private float duration_ = -1F;
      public boolean hasDuration() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public float getDuration() {
        return duration_;
      }
      public Builder setDuration(float value) {
        bitField0_ |= 0x00000100;
        duration_ = value;
        onChanged();
        return this;
      }
      public Builder clearDuration() {
        bitField0_ = (bitField0_ & ~0x00000100);
        duration_ = -1F;
        onChanged();
        return this;
      }
      
      // optional int32 caster = 10;
      private int caster_ ;
      public boolean hasCaster() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      public int getCaster() {
        return caster_;
      }
      public Builder setCaster(int value) {
        bitField0_ |= 0x00000200;
        caster_ = value;
        onChanged();
        return this;
      }
      public Builder clearCaster() {
        bitField0_ = (bitField0_ & ~0x00000200);
        caster_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 ability = 11;
      private int ability_ ;
      public boolean hasAbility() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      public int getAbility() {
        return ability_;
      }
      public Builder setAbility(int value) {
        bitField0_ |= 0x00000400;
        ability_ = value;
        onChanged();
        return this;
      }
      public Builder clearAbility() {
        bitField0_ = (bitField0_ & ~0x00000400);
        ability_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 armor = 12;
      private int armor_ ;
      public boolean hasArmor() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      public int getArmor() {
        return armor_;
      }
      public Builder setArmor(int value) {
        bitField0_ |= 0x00000800;
        armor_ = value;
        onChanged();
        return this;
      }
      public Builder clearArmor() {
        bitField0_ = (bitField0_ & ~0x00000800);
        armor_ = 0;
        onChanged();
        return this;
      }
      
      // optional float fade_time = 13;
      private float fadeTime_ ;
      public boolean hasFadeTime() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      public float getFadeTime() {
        return fadeTime_;
      }
      public Builder setFadeTime(float value) {
        bitField0_ |= 0x00001000;
        fadeTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearFadeTime() {
        bitField0_ = (bitField0_ & ~0x00001000);
        fadeTime_ = 0F;
        onChanged();
        return this;
      }
      
      // optional bool subtle = 14;
      private boolean subtle_ ;
      public boolean hasSubtle() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      public boolean getSubtle() {
        return subtle_;
      }
      public Builder setSubtle(boolean value) {
        bitField0_ |= 0x00002000;
        subtle_ = value;
        onChanged();
        return this;
      }
      public Builder clearSubtle() {
        bitField0_ = (bitField0_ & ~0x00002000);
        subtle_ = false;
        onChanged();
        return this;
      }
      
      // optional float channel_time = 15;
      private float channelTime_ ;
      public boolean hasChannelTime() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      public float getChannelTime() {
        return channelTime_;
      }
      public Builder setChannelTime(float value) {
        bitField0_ |= 0x00004000;
        channelTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearChannelTime() {
        bitField0_ = (bitField0_ & ~0x00004000);
        channelTime_ = 0F;
        onChanged();
        return this;
      }
      
      // optional .CMsgVector v_start = 16;
      private Networkbasetypes.CMsgVector vStart_ = Networkbasetypes.CMsgVector.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          Networkbasetypes.CMsgVector, Networkbasetypes.CMsgVector.Builder, Networkbasetypes.CMsgVectorOrBuilder> vStartBuilder_;
      public boolean hasVStart() {
        return ((bitField0_ & 0x00008000) == 0x00008000);
      }
      public Networkbasetypes.CMsgVector getVStart() {
        if (vStartBuilder_ == null) {
          return vStart_;
        } else {
          return vStartBuilder_.getMessage();
        }
      }
      public Builder setVStart(Networkbasetypes.CMsgVector value) {
        if (vStartBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          vStart_ = value;
          onChanged();
        } else {
          vStartBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00008000;
        return this;
      }
      public Builder setVStart(
          Networkbasetypes.CMsgVector.Builder builderForValue) {
        if (vStartBuilder_ == null) {
          vStart_ = builderForValue.build();
          onChanged();
        } else {
          vStartBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00008000;
        return this;
      }
      public Builder mergeVStart(Networkbasetypes.CMsgVector value) {
        if (vStartBuilder_ == null) {
          if (((bitField0_ & 0x00008000) == 0x00008000) &&
              vStart_ != Networkbasetypes.CMsgVector.getDefaultInstance()) {
            vStart_ =
              Networkbasetypes.CMsgVector.newBuilder(vStart_).mergeFrom(value).buildPartial();
          } else {
            vStart_ = value;
          }
          onChanged();
        } else {
          vStartBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00008000;
        return this;
      }
      public Builder clearVStart() {
        if (vStartBuilder_ == null) {
          vStart_ = Networkbasetypes.CMsgVector.getDefaultInstance();
          onChanged();
        } else {
          vStartBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00008000);
        return this;
      }
      public Networkbasetypes.CMsgVector.Builder getVStartBuilder() {
        bitField0_ |= 0x00008000;
        onChanged();
        return getVStartFieldBuilder().getBuilder();
      }
      public Networkbasetypes.CMsgVectorOrBuilder getVStartOrBuilder() {
        if (vStartBuilder_ != null) {
          return vStartBuilder_.getMessageOrBuilder();
        } else {
          return vStart_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          Networkbasetypes.CMsgVector, Networkbasetypes.CMsgVector.Builder, Networkbasetypes.CMsgVectorOrBuilder> 
          getVStartFieldBuilder() {
        if (vStartBuilder_ == null) {
          vStartBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              Networkbasetypes.CMsgVector, Networkbasetypes.CMsgVector.Builder, Networkbasetypes.CMsgVectorOrBuilder>(
                  vStart_,
                  getParentForChildren(),
                  isClean());
          vStart_ = null;
        }
        return vStartBuilder_;
      }
      
      // optional .CMsgVector v_end = 17;
      private Networkbasetypes.CMsgVector vEnd_ = Networkbasetypes.CMsgVector.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          Networkbasetypes.CMsgVector, Networkbasetypes.CMsgVector.Builder, Networkbasetypes.CMsgVectorOrBuilder> vEndBuilder_;
      public boolean hasVEnd() {
        return ((bitField0_ & 0x00010000) == 0x00010000);
      }
      public Networkbasetypes.CMsgVector getVEnd() {
        if (vEndBuilder_ == null) {
          return vEnd_;
        } else {
          return vEndBuilder_.getMessage();
        }
      }
      public Builder setVEnd(Networkbasetypes.CMsgVector value) {
        if (vEndBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          vEnd_ = value;
          onChanged();
        } else {
          vEndBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00010000;
        return this;
      }
      public Builder setVEnd(
          Networkbasetypes.CMsgVector.Builder builderForValue) {
        if (vEndBuilder_ == null) {
          vEnd_ = builderForValue.build();
          onChanged();
        } else {
          vEndBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00010000;
        return this;
      }
      public Builder mergeVEnd(Networkbasetypes.CMsgVector value) {
        if (vEndBuilder_ == null) {
          if (((bitField0_ & 0x00010000) == 0x00010000) &&
              vEnd_ != Networkbasetypes.CMsgVector.getDefaultInstance()) {
            vEnd_ =
              Networkbasetypes.CMsgVector.newBuilder(vEnd_).mergeFrom(value).buildPartial();
          } else {
            vEnd_ = value;
          }
          onChanged();
        } else {
          vEndBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00010000;
        return this;
      }
      public Builder clearVEnd() {
        if (vEndBuilder_ == null) {
          vEnd_ = Networkbasetypes.CMsgVector.getDefaultInstance();
          onChanged();
        } else {
          vEndBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00010000);
        return this;
      }
      public Networkbasetypes.CMsgVector.Builder getVEndBuilder() {
        bitField0_ |= 0x00010000;
        onChanged();
        return getVEndFieldBuilder().getBuilder();
      }
      public Networkbasetypes.CMsgVectorOrBuilder getVEndOrBuilder() {
        if (vEndBuilder_ != null) {
          return vEndBuilder_.getMessageOrBuilder();
        } else {
          return vEnd_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          Networkbasetypes.CMsgVector, Networkbasetypes.CMsgVector.Builder, Networkbasetypes.CMsgVectorOrBuilder> 
          getVEndFieldBuilder() {
        if (vEndBuilder_ == null) {
          vEndBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              Networkbasetypes.CMsgVector, Networkbasetypes.CMsgVector.Builder, Networkbasetypes.CMsgVectorOrBuilder>(
                  vEnd_,
                  getParentForChildren(),
                  isClean());
          vEnd_ = null;
        }
        return vEndBuilder_;
      }
      
      // optional string portal_loop_appear = 18;
      private java.lang.Object portalLoopAppear_ = "";
      public boolean hasPortalLoopAppear() {
        return ((bitField0_ & 0x00020000) == 0x00020000);
      }
      public String getPortalLoopAppear() {
        java.lang.Object ref = portalLoopAppear_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          portalLoopAppear_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPortalLoopAppear(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00020000;
        portalLoopAppear_ = value;
        onChanged();
        return this;
      }
      public Builder clearPortalLoopAppear() {
        bitField0_ = (bitField0_ & ~0x00020000);
        portalLoopAppear_ = getDefaultInstance().getPortalLoopAppear();
        onChanged();
        return this;
      }
      void setPortalLoopAppear(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00020000;
        portalLoopAppear_ = value;
        onChanged();
      }
      
      // optional string portal_loop_disappear = 19;
      private java.lang.Object portalLoopDisappear_ = "";
      public boolean hasPortalLoopDisappear() {
        return ((bitField0_ & 0x00040000) == 0x00040000);
      }
      public String getPortalLoopDisappear() {
        java.lang.Object ref = portalLoopDisappear_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          portalLoopDisappear_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPortalLoopDisappear(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00040000;
        portalLoopDisappear_ = value;
        onChanged();
        return this;
      }
      public Builder clearPortalLoopDisappear() {
        bitField0_ = (bitField0_ & ~0x00040000);
        portalLoopDisappear_ = getDefaultInstance().getPortalLoopDisappear();
        onChanged();
        return this;
      }
      void setPortalLoopDisappear(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00040000;
        portalLoopDisappear_ = value;
        onChanged();
      }
      
      // optional string hero_loop_appear = 20;
      private java.lang.Object heroLoopAppear_ = "";
      public boolean hasHeroLoopAppear() {
        return ((bitField0_ & 0x00080000) == 0x00080000);
      }
      public String getHeroLoopAppear() {
        java.lang.Object ref = heroLoopAppear_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          heroLoopAppear_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setHeroLoopAppear(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00080000;
        heroLoopAppear_ = value;
        onChanged();
        return this;
      }
      public Builder clearHeroLoopAppear() {
        bitField0_ = (bitField0_ & ~0x00080000);
        heroLoopAppear_ = getDefaultInstance().getHeroLoopAppear();
        onChanged();
        return this;
      }
      void setHeroLoopAppear(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00080000;
        heroLoopAppear_ = value;
        onChanged();
      }
      
      // optional string hero_loop_disappear = 21;
      private java.lang.Object heroLoopDisappear_ = "";
      public boolean hasHeroLoopDisappear() {
        return ((bitField0_ & 0x00100000) == 0x00100000);
      }
      public String getHeroLoopDisappear() {
        java.lang.Object ref = heroLoopDisappear_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          heroLoopDisappear_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setHeroLoopDisappear(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00100000;
        heroLoopDisappear_ = value;
        onChanged();
        return this;
      }
      public Builder clearHeroLoopDisappear() {
        bitField0_ = (bitField0_ & ~0x00100000);
        heroLoopDisappear_ = getDefaultInstance().getHeroLoopDisappear();
        onChanged();
        return this;
      }
      void setHeroLoopDisappear(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00100000;
        heroLoopDisappear_ = value;
        onChanged();
      }
      
      // optional int32 movement_speed = 22;
      private int movementSpeed_ ;
      public boolean hasMovementSpeed() {
        return ((bitField0_ & 0x00200000) == 0x00200000);
      }
      public int getMovementSpeed() {
        return movementSpeed_;
      }
      public Builder setMovementSpeed(int value) {
        bitField0_ |= 0x00200000;
        movementSpeed_ = value;
        onChanged();
        return this;
      }
      public Builder clearMovementSpeed() {
        bitField0_ = (bitField0_ & ~0x00200000);
        movementSpeed_ = 0;
        onChanged();
        return this;
      }
      
      // optional bool aura = 23;
      private boolean aura_ ;
      public boolean hasAura() {
        return ((bitField0_ & 0x00400000) == 0x00400000);
      }
      public boolean getAura() {
        return aura_;
      }
      public Builder setAura(boolean value) {
        bitField0_ |= 0x00400000;
        aura_ = value;
        onChanged();
        return this;
      }
      public Builder clearAura() {
        bitField0_ = (bitField0_ & ~0x00400000);
        aura_ = false;
        onChanged();
        return this;
      }
      
      // optional int32 activity = 24;
      private int activity_ ;
      public boolean hasActivity() {
        return ((bitField0_ & 0x00800000) == 0x00800000);
      }
      public int getActivity() {
        return activity_;
      }
      public Builder setActivity(int value) {
        bitField0_ |= 0x00800000;
        activity_ = value;
        onChanged();
        return this;
      }
      public Builder clearActivity() {
        bitField0_ = (bitField0_ & ~0x00800000);
        activity_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 damage = 25;
      private int damage_ ;
      public boolean hasDamage() {
        return ((bitField0_ & 0x01000000) == 0x01000000);
      }
      public int getDamage() {
        return damage_;
      }
      public Builder setDamage(int value) {
        bitField0_ |= 0x01000000;
        damage_ = value;
        onChanged();
        return this;
      }
      public Builder clearDamage() {
        bitField0_ = (bitField0_ & ~0x01000000);
        damage_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 range = 26;
      private int range_ ;
      public boolean hasRange() {
        return ((bitField0_ & 0x02000000) == 0x02000000);
      }
      public int getRange() {
        return range_;
      }
      public Builder setRange(int value) {
        bitField0_ |= 0x02000000;
        range_ = value;
        onChanged();
        return this;
      }
      public Builder clearRange() {
        bitField0_ = (bitField0_ & ~0x02000000);
        range_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 dd_modifier_index = 27;
      private int ddModifierIndex_ ;
      public boolean hasDdModifierIndex() {
        return ((bitField0_ & 0x04000000) == 0x04000000);
      }
      public int getDdModifierIndex() {
        return ddModifierIndex_;
      }
      public Builder setDdModifierIndex(int value) {
        bitField0_ |= 0x04000000;
        ddModifierIndex_ = value;
        onChanged();
        return this;
      }
      public Builder clearDdModifierIndex() {
        bitField0_ = (bitField0_ & ~0x04000000);
        ddModifierIndex_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 dd_ability_index = 28;
      private int ddAbilityIndex_ ;
      public boolean hasDdAbilityIndex() {
        return ((bitField0_ & 0x08000000) == 0x08000000);
      }
      public int getDdAbilityIndex() {
        return ddAbilityIndex_;
      }
      public Builder setDdAbilityIndex(int value) {
        bitField0_ |= 0x08000000;
        ddAbilityIndex_ = value;
        onChanged();
        return this;
      }
      public Builder clearDdAbilityIndex() {
        bitField0_ = (bitField0_ & ~0x08000000);
        ddAbilityIndex_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:CDOTAModifierBuffTableEntry)
    }
    
    static {
      defaultInstance = new CDOTAModifierBuffTableEntry(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:CDOTAModifierBuffTableEntry)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CDOTAModifierBuffTableEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CDOTAModifierBuffTableEntry_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024dota_modifiers.proto\032 google/protobuf/" +
      "descriptor.proto\032\026networkbasetypes.proto" +
      "\"\262\005\n\033CDOTAModifierBuffTableEntry\022N\n\nentr" +
      "y_type\030\001 \002(\0162\031.DOTA_MODIFIER_ENTRY_TYPE:" +
      "\037DOTA_MODIFIER_ENTRY_TYPE_ACTIVE\022\016\n\006pare" +
      "nt\030\002 \002(\005\022\r\n\005index\030\003 \002(\005\022\022\n\nserial_num\030\004 " +
      "\002(\005\022\026\n\016modifier_class\030\005 \001(\005\022\025\n\rability_l" +
      "evel\030\006 \001(\005\022\023\n\013stack_count\030\007 \001(\005\022\025\n\rcreat" +
      "ion_time\030\010 \001(\002\022\024\n\010duration\030\t \001(\002:\002-1\022\016\n\006" +
      "caster\030\n \001(\005\022\017\n\007ability\030\013 \001(\005\022\r\n\005armor\030\014",
      " \001(\005\022\021\n\tfade_time\030\r \001(\002\022\016\n\006subtle\030\016 \001(\010\022" +
      "\024\n\014channel_time\030\017 \001(\002\022\034\n\007v_start\030\020 \001(\0132\013" +
      ".CMsgVector\022\032\n\005v_end\030\021 \001(\0132\013.CMsgVector\022" +
      "\032\n\022portal_loop_appear\030\022 \001(\t\022\035\n\025portal_lo" +
      "op_disappear\030\023 \001(\t\022\030\n\020hero_loop_appear\030\024" +
      " \001(\t\022\033\n\023hero_loop_disappear\030\025 \001(\t\022\026\n\016mov" +
      "ement_speed\030\026 \001(\005\022\014\n\004aura\030\027 \001(\010\022\020\n\010activ" +
      "ity\030\030 \001(\005\022\016\n\006damage\030\031 \001(\005\022\r\n\005range\030\032 \001(\005" +
      "\022\031\n\021dd_modifier_index\030\033 \001(\005\022\030\n\020dd_abilit" +
      "y_index\030\034 \001(\005*e\n\030DOTA_MODIFIER_ENTRY_TYP",
      "E\022#\n\037DOTA_MODIFIER_ENTRY_TYPE_ACTIVE\020\001\022$" +
      "\n DOTA_MODIFIER_ENTRY_TYPE_REMOVED\020\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_CDOTAModifierBuffTableEntry_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_CDOTAModifierBuffTableEntry_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_CDOTAModifierBuffTableEntry_descriptor,
              new java.lang.String[] { "EntryType", "Parent", "Index", "SerialNum", "ModifierClass", "AbilityLevel", "StackCount", "CreationTime", "Duration", "Caster", "Ability", "Armor", "FadeTime", "Subtle", "ChannelTime", "VStart", "VEnd", "PortalLoopAppear", "PortalLoopDisappear", "HeroLoopAppear", "HeroLoopDisappear", "MovementSpeed", "Aura", "Activity", "Damage", "Range", "DdModifierIndex", "DdAbilityIndex", },
              DotaModifiers.CDOTAModifierBuffTableEntry.class,
              DotaModifiers.CDOTAModifierBuffTableEntry.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
          Networkbasetypes.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
